//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalKabaRest.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterfaceIn
    {
        public int InterfaceInId { get; set; }
        public int InterfaceID { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string RequestData { get; set; }
        public string ErrorMsg { get; set; }
        public Nullable<int> StatusId { get; set; }
    }
}
