//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalKabaRest.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LocalServicesDBEntities : DbContext
    {
        public LocalServicesDBEntities()
            : base("name=LocalServicesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<InterfaceIn> InterfaceIns { get; set; }
    
        public virtual ObjectResult<GetPrvCaseDetails_Result> GetPrvCaseDetails(Nullable<double> inLongitude, Nullable<double> inLatitude, Nullable<int> inRadius)
        {
            var inLongitudeParameter = inLongitude.HasValue ?
                new ObjectParameter("inLongitude", inLongitude) :
                new ObjectParameter("inLongitude", typeof(double));
    
            var inLatitudeParameter = inLatitude.HasValue ?
                new ObjectParameter("inLatitude", inLatitude) :
                new ObjectParameter("inLatitude", typeof(double));
    
            var inRadiusParameter = inRadius.HasValue ?
                new ObjectParameter("inRadius", inRadius) :
                new ObjectParameter("inRadius", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPrvCaseDetails_Result>("GetPrvCaseDetails", inLongitudeParameter, inLatitudeParameter, inRadiusParameter);
        }
    
        public virtual ObjectResult<GetPrvContacts_Result> GetPrvContacts(Nullable<int> inPrvId)
        {
            var inPrvIdParameter = inPrvId.HasValue ?
                new ObjectParameter("inPrvId", inPrvId) :
                new ObjectParameter("inPrvId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPrvContacts_Result>("GetPrvContacts", inPrvIdParameter);
        }
    
        public virtual ObjectResult<GetPrvOperationalInfo_Result> GetPrvOperationalInfo(Nullable<int> inPrvId)
        {
            var inPrvIdParameter = inPrvId.HasValue ?
                new ObjectParameter("inPrvId", inPrvId) :
                new ObjectParameter("inPrvId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPrvOperationalInfo_Result>("GetPrvOperationalInfo", inPrvIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SetInterfaceIn(string inRequestData, string inErrorMsg, Nullable<int> inStatusId)
        {
            var inRequestDataParameter = inRequestData != null ?
                new ObjectParameter("inRequestData", inRequestData) :
                new ObjectParameter("inRequestData", typeof(string));
    
            var inErrorMsgParameter = inErrorMsg != null ?
                new ObjectParameter("inErrorMsg", inErrorMsg) :
                new ObjectParameter("inErrorMsg", typeof(string));
    
            var inStatusIdParameter = inStatusId.HasValue ?
                new ObjectParameter("inStatusId", inStatusId) :
                new ObjectParameter("inStatusId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SetInterfaceIn", inRequestDataParameter, inErrorMsgParameter, inStatusIdParameter);
        }
    }
}
